package me.samuelh2005.lite_economy.commands.arguments;

import java.util.List;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.function.Function;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.mojang.brigadier.StringReader;
import com.mojang.brigadier.arguments.ArgumentType;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.exceptions.CommandSyntaxException;
import com.mojang.brigadier.exceptions.SimpleCommandExceptionType;
import com.mojang.brigadier.suggestion.Suggestions;
import com.mojang.brigadier.suggestion.SuggestionsBuilder;

import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.SharedSuggestionProvider;
import net.minecraft.network.chat.Component;

/**
 * A Brigadier argument type that accepts a quoted string in the format {@code "Name (uuid)"} and
 * parses the UUID from the trailing {@code (uuid)} portion. Suggestions are generated by a
 * context-aware function that receives the current {@link CommandContext} and returns a list of
 * {@link UUIDNameable} objects, producing {@code "Name (uuid)"} strings that this argument type
 * can parse.
 */
public final class NamedUUIDArgumentType implements ArgumentType<UUID> {
    private static final Pattern UUID_SUFFIX_PATTERN = Pattern.compile("\\(([0-9a-fA-F\\-]{36})\\)\\s*$");
    private static final SimpleCommandExceptionType INVALID_FORMAT = new SimpleCommandExceptionType(
        Component.literal("Expected format: \"Name (uuid)\"")
    );

    private final Function<CommandContext<CommandSourceStack>, List<? extends UUIDNameable>> suggestionsFunction;

    private NamedUUIDArgumentType(Function<CommandContext<CommandSourceStack>, List<? extends UUIDNameable>> suggestionsFunction) {
        this.suggestionsFunction = suggestionsFunction;
    }

    public static NamedUUIDArgumentType namedUUID(Function<CommandContext<CommandSourceStack>, List<? extends UUIDNameable>> suggestionsFunction) {
        return new NamedUUIDArgumentType(suggestionsFunction);
    }

    public static UUID getUUID(CommandContext<?> context, String name) {
        return context.getArgument(name, UUID.class);
    }

    @Override
    public UUID parse(StringReader reader) throws CommandSyntaxException {
        String raw = reader.readQuotedString();
        Matcher matcher = UUID_SUFFIX_PATTERN.matcher(raw);
        if (!matcher.find()) {
            throw INVALID_FORMAT.createWithContext(reader);
        }
        try {
            return UUID.fromString(matcher.group(1));
        } catch (IllegalArgumentException e) {
            throw INVALID_FORMAT.createWithContext(reader);
        }
    }

    @Override
    @SuppressWarnings("unchecked")
    public <S> CompletableFuture<Suggestions> listSuggestions(CommandContext<S> context, SuggestionsBuilder builder) {
        List<String> suggestions = suggestionsFunction.apply((CommandContext<CommandSourceStack>) context).stream()
            .map(item -> "\"" + item.getDisplayName().replace("\\", "\\\\").replace("\"", "\\\"") + " (" + item.getId() + ")\"")
            .toList();
        return SharedSuggestionProvider.suggest(suggestions, builder);
    }
}
